apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kong
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: kong
    spec:
      containers:
      - image: haufelexware/wicked.kong:0.11.7
        imagePullPolicy: Always
        name: kong
        readinessProbe:
          exec:
            command:
              - kong
              - health
        ports:
        - name: "gateway"
          containerPort: 8000
          protocol: TCP
        - name: "admin"
          containerPort: 8001
          protocol: TCP
        - name: "advertise"
          containerPort: 7946
          protocol: TCP
        - name: "advertiseudp"
          containerPort: 7946
          protocol: UDP
      restartPolicy: Always
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kong-database
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: kong-database
    spec:
      containers:
      - env:
        - name: POSTGRES_USER
          value: kong
        - name: POSTGRES_PASSWORD
          value: kong
        image: postgres:9.6
        name: kong-database
        ports:
        - name: "psql"
          containerPort: 5432
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: kong-db-data
      restartPolicy: Always
      volumes:
      - name: kong-db-data
        emptyDir: {}
#        persistentVolumeClaim:
#          claimName: idesk-apim-postgres
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: kong
  name: kong
spec:
  ports:
  - name: "admin"
    port: 8001
    protocol: TCP
  selector:
    service: kong
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: kong
  name: kong-gw
spec:
  ports:
  - name: "gateway"
    port: 8000
    protocol: TCP
  selector:
    service: kong
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: kong-database
  name: kong-database
spec:
  ports:
  - name: "psql"
    port: 5432
    protocol: TCP
  selector:
    service: kong-database
